import './style.scss';
import './js/main-created';
import './js/user-registration';
import './js/menu';
import './js/login-and-registration';
import './js/add-modal-show';
import './js/add-modal-categories';
import './js/add-modal-valid';
import './js/add-modal-preview';
import './js/add-modal-post';
// import './js/add-async-post';
// import './js/post';
// import './js/postFetch';
import './js/add-del-favourite';
// import './js/add-favourites-into-api';
import './js/add-favourites-into-page';
// import './js/delete-favourites-from-api&page';
import './js/advert-Close-Open';
import './js/advert-logic';
import './js/search-modal';
import './js/my-office-or-auth';
